function [feasRateNonRobust,...
    feasRateRobust, ...
    rateUnlicensedNonRobust, ...
    rateLicensedNonRobust, ...
    rateUnlicensedRobust, ...
    rateLicensedRobust, ...
    ExcessIntefpPowerdNonRobust, ...
    ExcessIntefpPowerdRobust, ...
    bfVec1, ...
    bfVec2, ...
    bfVec3, ...
    iters, ...
    LicenseduserLocs, ...
    UnlicenseduserLocs] = matrices(err,alpha,expr)

feasRateNonRobust = zeros(err,alpha,expr);
feasRateRobust = zeros(err,alpha,expr);

rateUnlicensedNonRobust = zeros(err,alpha,expr);
rateLicensedNonRobust = zeros(err,alpha,expr);
rateUnlicensedRobust = zeros(err,alpha,expr);
rateLicensedRobust = zeros(err,alpha,expr);
ExcessIntefpPowerdNonRobust = zeros(err,alpha,expr);
ExcessIntefpPowerdRobust = zeros(err,alpha,expr);

bfVec1 = zeros(err,alpha,expr);
bfVec2 = zeros(err,alpha,expr);
bfVec3 = zeros(err,alpha,expr);

iters = NaN*ones(err,alpha,expr);

LicenseduserLocs = zeros(expr,2);
UnlicenseduserLocs = zeros(expr,2);
end